# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170413_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='stealattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stealattempt',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'WAITING_FOR_THIEF_END'), (2, 'WAITING_FOR_DEFENSE_START'), (3, 'WAITING_FOR_DEFENSE_END'), (4, 'COMPLETE'), (5, 'EXPIRED')], default=0),
        ),
        migrations.AlterField(
            model_name='stealattempt',
            name='thief_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
