# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170415_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steal_cool_down_seconds',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
    ]
